### ISSUE TITLE
Getting instruction on how to remove heatit, when trying to add it

### ISSUE THREAD

**Issue by catohauk** [Heatit-Controls/no.ThermoFloor#28]
Hi.

I'm trying to add the Z-wave thermostat (not the 1.92v). When doing so, the instructions only explain how I can remove the thermostat, not how to add it. 

Please advise on how to add the device. 

![Heait add in homey](https://user-images.githubusercontent.com/45530539/70895884-04b7fc00-1ff0-11ea-9076-e977da83259d.png)

Best regards,
Cato

**Comment by TedTolboom** [comment]
@catohauk this is apperantly a non communicated change on Homey firmware side; to force the removal of a device first (step 1, in above screenshot) and then include it (step 2).
I also learned this yesterday, while debugging a device.

Just follow the instructions shown, first trigger the removal, then the screen will change to the inclusion instructions (almost the same) and the device will be included.

**Comment by catohauk** [comment]
Allright. I'll try that. Thanks Ted

**Comment by RAN-dale** [comment]
I have the same problem. I have tryed 100 times, and the same is happening. I also have Heatit with extern sensor. I got the same instrution that explain how too remove. It also shut down/ reset and err4. I have changed settings to ekstern sensor and have too set the settings again...

**Comment by Madaxhub** [comment]
I have the same problem. Could you please update the app 😊

**Comment by HeatitControls** [comment]
@RAN-dale step 1 of inclusion is removing the device and after you've proceeded with that it will show you how to include it.
