### ISSUE TITLE
Z-TRM2fx not updating temperature 

### ISSUE THREAD

**Issue by nibors76** [Heatit-Controls/no.ThermoFloor#33]
Hi Ted, just changed a thermostat from the old Heatit to z-trm2fx, and there is a problem straight away...
Can see voltage etc change now and then, but the temperature does not update (it is set to 60 s).
This means that the cable will still heat, way over the set point... restarting your app/or Homey will update the temperature reading...

Why...?
Is it a bug somewhere,  or is it a problem with the include prosess?

**Comment by TedTolboom** [comment]
@nibors76 to start / prevent a common misunderstanding.
> This means that the cable will still heat, way over the set point...
That is not true. The heating logic resides in the thermostat itself. Communication between Homey and the thermostat is only on reporting the state (temperature) or controlling the mode / setpoint. So Homey not receiving the temperature report, does not mean that the thermostat will keep heating. The thermostat will switch off when the setpoint has been reached / exceeded.

On the issue of not reporting; does your setup use the internal sensor / floor sensor or an external one? Are none of the sensors showing any data?
