### ISSUE TITLE
Device Spesific -Energy, continuously reporting on

### ISSUE THREAD

**Issue by lkaasbrenn** [Heatit-Controls/no.ThermoFloor#35]
Hi,
Thanks for making this app!
I have the HeatIt thermostat without energy metering. Since I know the usage, I entered 600w for the 
Constant Power Usage in Advanced Settings. I expected it to report 600W usage only when the heating is on, but it reports 600w continuously. Even when I turn the themostat off.
I guess this is a bug?
Best Regards 
LK

**Comment by aivus** [comment]
Seems it happens because the device doesn't have `onoff` capability, but Homey requires it:
https://apps-sdk-v2.developer.athom.com/tutorial-Drivers-Energy.html

So, any devices without `onoff` capability uses constant value as a measured power.
