### ISSUE TITLE
z-push button 8 can pair but not trigger flows in Homey

### ISSUE THREAD

**Issue by Matbj** [Heatit-Controls/no.ThermoFloor#63]
I'm successfully able to pair two new z-push button 8 devices with my Homey. However I'm not able to trigger any flows (test button works). I have another z-push button 8 that was paired from before and that one works perfectly. 

In the advanced settings I can see that the old (functional) one has a check mark under "Secure". The new ones however get: "S2 (Unauthenticated)".

Any clues? Is it the new Homey 7.0 version that broke it?

**Comment by HeatitControls** [comment]
Hi, do these devices include as Z-push buttons or as generic Z-Wave devices?

**Comment by Matbj** [comment]
Hi! I added them as Z-push buttons using the Heatit app in Homey. 

Now I've also tried a brand new z-push button 4 with same result.

**Comment by Matbj** [comment]
Okay, I just now tried adding the button 4 as a Homey generic Z-wave device. I ended up with the exact same result unfortunately.

**Comment by HeatitControls** [comment]
@Matbj What do you see on manufacturer ID?

**Comment by Matbj** [comment]
I see: 411

![Screenshot_20210701-222614](https://user-images.githubusercontent.com/8516193/124185590-7749d900-dabb-11eb-8329-04783aa2da73.jpg)

**Comment by HeatitControls** [comment]
You suggest it might be that it is version 7.0 that broke it. Does that mean it worked before?

**Comment by Matbj** [comment]
Yes, I previously paired a z-push button 8 (~4 weeks ago). Which still works as should.

**Comment by Matbj** [comment]
Closing issue as it got solved by Homey 7.0.1
