### ISSUE TITLE
Zm single relay 16a

### ISSUE THREAD

**Issue by Rens-H** [Heatit-Controls/no.ThermoFloor#67]
Hi @TedTolboom 

Can you add support for the heatit zm single relay 16A ?

![IMG_20210824_143819](https://user-images.githubusercontent.com/80253879/130618129-29aee058-0a36-449b-8954-9a4ee2a25102.jpg)

Thx

Rens Hoekema

**Comment by Ctech83** [comment]
I would love to see that as well. Anything you need that I can help with?

**Comment by Tsju** [comment]
Same here, doesn't support it yet. Will there be any answer here?

**Comment by HeatitControls** [comment]
Support has been added
