### ISSUE TITLE
Homey bridge support

### ISSUE THREAD

**Issue by Lunken007** [Heatit-Controls/no.ThermoFloor#71]
Can you please add support for the new homey bridge?

**Comment by rnrbrste** [comment]
Agree! Would be awesome now when the beta program is rolled out world wide. I think this should be prioritized. Most of the biggest brands have done this, and if Heatit gets this support, my whole house is Bridge compatible.

**Comment by HeatitControls** [comment]
Hi, we are working on adding Bridge support

**Comment by varleg** [comment]
That is absolutely awesome! I love the design of the heatit thermostat, and I don't want to switch to another brand just to have it bridge compatible.

**Comment by Lunken007** [comment]
This is great news! Do you have any idea when this will be released? 😊
