### ISSUE TITLE
TRM3s become unreachable after 24-48 hours

### ISSUE THREAD

**Issue by Strauman** [Heatit-Controls/no.ThermoFloor#72]
Hi!
I recently switched out all my 5 manual thermostats to your TRM3 thermostats for my floor heating. However, they all become unreachable within 48 hours and have to be paired with Homey again. Homey is not able to communicate with them at all. Other Z-Wave devices seem to work fine.

I also see other people reporting issues in the athom community, and mention that behaviour changed after the Homey 7.1.5 update. I have not had the thermostats long enough to say for sure.

Please fix this, as this renders my thermostats basically a waste :/

https://community.athom.com/t/heatit-z-wave-app-v2-7-1/49914/55

**Comment by Strauman** [comment]
Daily disabling and waiting 20 sec before enabling have seemed to solve the problem. Restarting app is not sufficient.

**Comment by Strauman** [comment]
It stopped working again. A new observation is that Homey does not recognize it upon removal. When I remove it, Homey says "This is not the device you were trying to remove, but we removed that instead".

**Comment by Barblo1986** [comment]
Hi, i have the same problem, whaiting for a update....

**Comment by HeatitControls** [comment]
Hi, please try updating the app. If this does not help please include the devices unsecure.
