### ISSUE TITLE
Typo in capability 

### ISSUE THREAD

**Issue by robertklep** [Heatit-Controls/no.ThermoFloor#76]
I was just browsing the code base for something unrelated when I noticed a comma instead of a period here:
https://github.com/Heatit-Controls/no.ThermoFloor/blob/ba05893d80976f552b50c3d4325ef941ff17bd48/drivers/TF_Thermostat_FW1.92/device.js#L32

**Comment by NilsBohr** [comment]
@robertklep 
Thank you, will be fixed
